name: CI Pipeline

on:
  push:
    branches:
      - main    # Branche principale
  pull_request:

jobs:
  test:
    name: Run Flutter Tests and Generate Documentation
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Étape 2 : Installer Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: stable

      # Étape 3 : Installer les dépendances
      - name: Install Dependencies
        run: flutter pub get

      # Étape 4 : Analyse du code
      - name: Analyze Code
        run: dart analyze

      # Étape 5 : Exécuter les tests
      - name: Run Tests
        run: flutter test

      # Étape 6 : Générer la documentation
      - name: Generate Documentation
        run: dart doc

      # Étape 7 : Sauvegarder la documentation comme artefact
      - name: Upload Documentation
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: doc/api

      # Étape 8 : Notification en cas d'échec
      - name: Notify on Failure
        if: failure()
        run: echo "Tests failed. Please check the pipeline logs."

      - name: Run tests
        run: dart test
